# a list of globs to exclude from scanning, for example:
# exclude:
#   - "/etc/**"
#   - "./out/**/*.json"
# SYFT_EXCLUDE env var / --exclude flag
#
# For studio-client plugins you can skip the scanning process
# because they are not supposed to introduce new dependencies.
# The dependencies in the lockfile are considered runtime dependencies.
# The actual version is determined by the studio-client application.
exclude:
  - "/studio-client/**"
